In [34]:
import pandas as pd

In [35]:
df = pd.read_csv('titanic.csv')

In [36]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875
...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 32.8+ KB

In [38]:
from sklearn.preprocessing import OrdinalEncoder
o = OrdinalEncoder()
df[['Name']] = o.fit_transform(df[['Name']])
df[['Sex']] = o.fit_transform(df[['Sex']])
df[['Ticket']] = o.fit_transform(df[['Ticket']])

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    float64
 4   Sex          418 non-null    float64
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    float64
 9   Fare         417 non-null    float64
dtypes: float64(5), int64(5)
memory usage: 32.8 KB

In [40]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,206.0,1.0,34.5,0,0,152.0,7.8292
1,893,1,3,403.0,0.0,47.0,1,0,221.0,7.0000
2,894,0,2,269.0,1.0,62.0,0,0,73.0,9.6875
3,895,0,3,408.0,1.0,27.0,0,0,147.0,8.6625
4,896,1,3,178.0,0.0,22.0,1,1,138.0,12.2875
...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,353.0,1.0,NaN,0,0,267.0,8.0500
414,1306,1,1,283.0,0.0,39.0,0,0,324.0,108.9000
415,1307,0,3,332.0,1.0,38.5,0,0,346.0,7.2500
416,1308,0,3,384.0,1.0,NaN,0,0,220.0,8.0500
417,1309,0,3,302.0,1.0,NaN,1,1,105.0,22.3583

In [41]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [42]:
x

     PassengerId  Pclass   Name  Sex   Age  SibSp  Parch  Ticket      Fare
0            892       3  206.0  1.0  34.5      0      0   152.0    7.8292
1            893       3  403.0  0.0  47.0      1      0   221.0    7.0000
2            894       2  269.0  1.0  62.0      0      0    73.0    9.6875
3            895       3  408.0  1.0  27.0      0      0   147.0    8.6625
4            896       3  178.0  0.0  22.0      1      1   138.0   12.2875
..           ...     ...    ...  ...   ...    ...    ...     ...       ...
413         1305       3  353.0  1.0   NaN      0      0   267.0    8.0500
414         1306       1  283.0  0.0  39.0      0      0   324.0  108.9000
415         1307       3  332.0  1.0  38.5      0      0   346.0    7.2500
416         1308       3  384.0  1.0   NaN      0      0   220.0    8.0500
417         1309       3  302.0  1.0   NaN      1      1   105.0   22.3583

[418 rows x 9 columns]

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-1.72791209,  0.87348191, -0.02071837, ..., -0.4002477 ,
        -0.26949361, -0.49781052],
       [-1.71962474,  0.87348191,  1.61188922, ..., -0.4002477 ,
         0.37293425, -0.51265996],
       [-1.71133739, -0.31581919,  0.50138456, ..., -0.4002477 ,
        -1.00502694, -0.46453181],
       ...,
       [ 1.71133739,  0.87348191,  1.0234875 , ..., -0.4002477 ,
         1.53675282, -0.50818292],
       [ 1.71962474,  0.87348191,  1.4544296 , ..., -0.4002477 ,
         0.3636237 , -0.4938564 ],
       [ 1.72791209,  0.87348191,  0.77486705, ...,  0.61989583,
        -0.70708939, -0.23762123]], shape=(418, 9))