In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('World University Rankings 2023-selected-columns.csv')

In [35]:
df

     University Rank  ... Research Score
0                  1  ...           99.7
1                  2  ...           99.0
2                  3  ...           99.5
3                  3  ...           96.7
4                  5  ...           93.6
...              ...  ...            ...
2336               -  ...           15.5
2337               -  ...           29.4
2338               -  ...           14.3
2339               -  ...           26.7
2340               -  ...           14.8

[2341 rows x 10 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2341 entries, 0 to 2340
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   University Rank          2341 non-null   object
 1   Name of University       2233 non-null   object
 2   Location                 2047 non-null   object
 3   No of student            2209 non-null   object
 4   No of student per staff  2208 non-null   float64
 5   International Student    2209 non-null   object
 6   Female:Male Ratio        2128 non-null   object
 7   OverAll Score            1799 non-null   object
 8   Teaching Score           1799 non-null   float64
 9   Research Score           1799 non-null   float64
dtypes: float64(3), object(7)
memory usage: 183.0+ KB

In [37]:
df.isnull().sum().sum()

np.int64(2638)

In [38]:
df.isnull().sum()

University Rank              0
Name of University         108
Location                   294
No of student              132
No of student per staff    133
International Student      132
Female:Male Ratio          213
OverAll Score              542
Teaching Score             542
Research Score             542
dtype: int64

In [39]:
df['Name of University']

0                        University of Oxford
1                          Harvard University
2                     University of Cambridge
3                         Stanford University
4       Massachusetts Institute of Technology
                        ...
2336       University of the West of Scotland
2337                    University of Windsor
2338              University of Wolverhampton
2339                  University of Wuppertal
2340      Xi’an Jiaotong-Liverpool University
Name: Name of University, Length: 2341, dtype: object

In [40]:
df['Name of University'] = df['Name of University'].fillna(df['Name of University'].mode()[0])

In [41]:
df['Name of University'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
2336    False
2337    False
2338    False
2339    False
2340    False
Name: Name of University, Length: 2341, dtype: bool

In [42]:
df['No of student'].isnull().sum()

np.int64(132)

In [43]:
df['No of student'].head(1000)

0      20,965
1      21,887
2      20,185
3      16,164
4      11,415
        ...
995     4,024
996    21,788
997     9,641
998    18,057
999    29,045
Name: No of student, Length: 1000, dtype: object

In [ ]:
df.describe()

       No of student per staff  Teaching Score  Research Score
count              2208.000000     1799.000000     1799.000000
mean                 19.000408       27.018010       23.016898
std                  12.132224       13.282243       16.763819
min                   0.400000       11.600000        7.400000
25%                  12.600000       18.000000       11.300000
50%                  16.600000       22.700000       17.000000
75%                  22.200000       31.850000       28.900000
max                 232.200000       94.800000       99.700000

In [ ]:
df['No of student'].unique()

array(['20,965', '21,887', '20,185', ..., '3,869', '4,906', nan],
      shape=(2137,), dtype=object)

In [ ]:
df['Location'] = df['Location'].fillna(df['Location'].mode()[0])